version: '2'

services:
  api:
    build: api
    command: npm start
    volumes:
      - ./api:/usr/app/
    environment:
      - PORT=3000
    ports:
      - "4021:3000"
    depends_on:
      - mongodb

  api-graphql:
    build: api-graphql
    command: npm start
    volumes:
      - ./api-graphql:/usr/app/
    environment:
      - PORT=3000
    ports:
      - "4022:3000"
    depends_on:
      - mongodb

  ember:
    build: ember
    command: npm start
    volumes:
      - ./ember:/usr/app/
    ports:
      - "4030:3000"

  vue-webpack:
    build: vue-webpack
    command: npm run dev
    volumes:
      - ./vue-webpack:/usr/app/
    ports:
      - "4031:8080"

  vue-vuex-webpack:
    build: vue-vuex-webpack
    command: npm run dev
    volumes:
      - ./vue-vuex-webpack:/usr/app/
    ports:
      - "4032:8080"

  mongodb:
    image: mongo:latest
    command: "mongod --smallfiles --logpath=/dev/null"
    volumes:
      - ./api/data/db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27018:27017"
